import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/shared/Navbar";
import Footer from "@/shared/Footer";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Victor - Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-full w-full overflow-x-hidden">
          <NavBar />
          <div className="mt-[60px]">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
