import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/shared/Navbar";
import Footer from "@/shared/Footer";
import SideBar from "@/shared/Sidebar";
import { AppProvider } from "./provider";
import { RootState } from "@/store/app-store";
import { useSelector } from "react-redux";
import AppLayout from "@/shared/AppLayout";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Victor - Frontend Developer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <AppLayout>{children}</AppLayout>
        </AppProvider>
      </body>
    </html>
  );
}
